### ISSUE TITLE
Tag a release

### ISSUE THREAD

**Issue by fprochazka** [brick/money#1]
Hi, I like your library and I would like to use it. Do you think you could tag `v0.1`? Thanks!

**Comment by VasekPurchart** [comment]
:+1:

**Comment by BenMorel** [comment]
I'm not quite ready for it yet, as I have not finalized my specs for the project. Expect a first beta release in the coming weeks/months though :)

**Comment by jkuchar** [comment]
Cool, looking forward for that :+1:

**Comment by fprochazka** [comment]
@BenMorel I'm looking forward to it!
