### ISSUE TITLE
Add explanation to README for import-currencies.php

### ISSUE THREAD

**Issue by raphaelstolt** [brick/money#10]
It's not really clear, at first sight, what the `import-currencies.php` is for, so a mention in the `README.md` would be helpful for project users. 

It also should be prolly moved into a dedicated `bin` directory, so it doesn't get confused with Git repository configuration files like `.travis.yml` or `.gitignore`.

A Composer [script](https://getcomposer.org/doc/articles/scripts.md) for it would also make it easier, clearer, and well documented for the library users.

**Comment by BenMorel** [comment]
It's actually clearly documented in the script itself:

> This script creates an array of currencies from a trusted source.
> The result of the script is exported in PHP format to be used by the library at runtime.
> This script is meant to be run by project maintainers, on a regular basis.

It should actually be export-ignored as well in #9!
