### ISSUE TITLE
Add suggested extension to Composer file

### ISSUE THREAD

**Issue by raphaelstolt** [brick/money#11]
Document (and soft enforce) the suggested usage of the `GMP`and `BCMath` extensions in the Composer file via [suggest](https://getcomposer.org/doc/04-schema.md#suggest).

**Comment by BenMorel** [comment]
This has been proposed in brick/math#5, but refused as you would still get the suggestion even though you have one of the two extensions installed, which is annoying.

If I missed a way to suggest one extension OR another, please feel free to reopen.
