### ISSUE TITLE
RoundingMode::AUTO?

### ISSUE THREAD

**Issue by MikeDaniel18** [brick/money#18]
Hi,

First off, I love this library, it's super intuitive and powerful.

One thing I have a problem with, however, is the rounding mode. Why isn't there an option to round to the nearest subunit (context sensitive of course)? It seems odd that I have to hardcode a RoundingMode or do the calculation myself.

For instance, your readme demostrates Rounding as such, where you're required to round either up or down: 
```
$money->plus('0.999', RoundingMode::DOWN); // USD 50.99

$money->minus('0.999', RoundingMode::UP); // USD 49.01
```
To me, unless you have a specific use case where you need to deliberately favour a particular rounding, under no circumstance would '0.999' ever be considered '0.99'.

Perhaps I am missing something, and if so I'd appreciate the pointer in the right direction.

Cheers,
Mike

**Comment by BenMorel** [comment]
Hi, you have [many rounding modes](https://github.com/brick/math/blob/master/src/RoundingMode.php) to choose from, not only `UP` and `DOWN`!

What you're looking for is most probably `RoundingMode::HALF_UP` or `HALF_EVEN`.

**Comment by MikeDaniel18** [comment]
And there I was, missing quite a lot. Case closed. Thank you very much, Benjamin, for highlighting my oversight.

Cheers,
Mike
