### ISSUE TITLE
Conditional chaining

### ISSUE THREAD

**Issue by khairahmanplus** [brick/money#20]
I have use case where i need to chain a lot of numbers based on true/false conditional. Idea is from method `when` in Laravel Framework.

https://github.com/laravel/framework/blob/5.8/src/Illuminate/Database/Concerns/BuildsQueries.php#L88

```php
$salary = '3000.70';
$employerContributeTax = true;
$employerContributeInsurance = true;

$gross = Money::for($salary)
    ->when($employerContributeTax, function ($salary) {
        return $salary->minus($someNumber);
    })
    ->when($employerContributeInsurance, function ($salary) {
        return $salary->minus($someNumberAgain);
    });
```

**Comment by BenMorel** [comment]
I'm sorry but I fail to see the value in this proposal.

Is the above equivalent to the following code?

```php
$salary = '3000.70';
$employerContributeTax = true;
$employerContributeInsurance = true;

$gross = Money::of($salary);

if ($employerContributeTax) {
    $salary = $salary->minus($someNumber);
}

if ($employerContributeInsurance) {
    $salary = $salary->minus($someNumberAgain);
}
```

If so, what's wrong with this approach?

**Comment by BenMorel** [comment]
Closing due to absence of feedback. Please feel free to comment if you think this should be reopened.
