### ISSUE TITLE
What is pros/cons in comparison with moneyphp/money

### ISSUE THREAD

**Issue by Insolita** [brick/money#28]
What is pros/cons in comparison with https://github.com/moneyphp/money  ?

**Comment by IP-Developer** [comment]
+1

**Comment by Nyratas** [comment]
+1

**Comment by kohlerdominik** [comment]
We started with moneyphp and we switched to brick/money, as, in my opinion, the design of brick/money is more flexible.

We use money without currency (Users can define a Project-wide currency, and then use this currency throughout the Project). So, actually currency is only handled when we show data to the User. But for a lot of calculations, storing in DB, etc, we still need to work with arbitrary numbers, and brick/money basing on brick/math makes this so easy.

**Comment by Nyratas** [comment]
Great summary @BenMorel. I'm considering moving my [compound prices](https://github.com/whitecube/php-prices) library to `brick/money`. Thank you!

**Comment by hopeseekr** [comment]
Compare to my project https://github.com/phpexperts/MoneyType. It looks extremely similar.

**Comment by iaicam** [comment]
@BenMorel I think you should add your comment to the readme since this will be a very common question and I personally didn't even think to look in the issues for the answer and only found this after being directed here.

**Comment by BenMorel** [comment]
@hopeseekr Thanks for the link, it's always interesting to see how others solve the same problem! I think the major difference between MoneyType and brick/money is that brick/money will by default have a scale that's per-currency (2 for EUR, USD etc.) and complain if you attempt to perform calculations that result in more decimal digits than configured (but provides [Contexts](https://github.com/brick/money#money-contexts) to customize this, and [RationalMoney](https://github.com/brick/money#advanced-calculations) to never round); this is was a big requirement when creating this library, to ensure that you always handle rounding where necessary, or get an exception.

@iaicam The primary aim of this library is not to be a competitor to moneyphp, so I won't make a paragraph there highlighting the differences. However, you're right that this is becoming a frequently asked question, so I will probably add a link to this issue, and try to keep it up to date! 👍

**Comment by BenMorel** [comment]
A link to this issue has been added to the [README](https://github.com/brick/money#faq).

**Comment by Sindbad2025** [comment]
<a href="https://www.aklny.store/">امدونه الاكيل</a>

<a href="https://www.aklny.store/search/label/%D8%A7%D9%84%D8%A7%D8%B7%D8%A8%D8%A7%D9%82%20%D8%A7%D9%84%D8%B1%D8%A6%D8%B3%D9%8A%D9%87">وصفات طبخ</a>

<a href="https://www.aklny.store/search/label/%D8%A7%D9%83%D9%84%D8%A7%D8%AA%20%D8%A7%D9%82%D8%AA%D8%B5%D8%A7%D8%AF%D9%8A%D9%87">شروحات</a>

<a href="https://www.aklny.store/search/label/%D8%A7%D9%83%D9%84%D8%A7%D8%AA%20%D8%B3%D9%88%D8%B1%D9%8A%D9%87">اكلات مصري</a>

<a href="https://www.aklny.store/search/label/%D8%AD%D9%84%D9%88%D9%8A%D8%A7%D8%AA">اكلات سوريا</a>

<a href="https://www.aklny.store/search/label/%D8%AC%D9%85%D8%A7%D9%84">مواقع</a>

<a href="https://www.aklny.store/search/label/%D9%85%D9%82%D8%A8%D8%A7%D9%84%D8%A7%D8%AA">اكلات مغربيه</a>

<a href="https://www.aklny.store/search/label/%D8%A7%D9%83%D9%84%D8%A7%D8%AA%20%D9%85%D8%BA%D8%B1%D8%A8%D8%A8%D9%87">منوعات </a>

<a href="https://www.aklny.store/search/label/%D9%85%D8%B4%D8%B1%D9%88%D8%A8%D8%A7%D8%AA">الصحه والجمال</a>
