### ISSUE TITLE
Feature: implement splitWithRemainder() & allocateWithRemainder()

### ISSUE THREAD

**Issue by BenMorel** [brick/money#39]
Same as `split()` and `allocate()`, but:

- don't spread the remainder on the first monies
- add another `Money` at the end of the array with the remainder

Taking the examples from the README:

```php
$money = Money::of(100, 'USD');
[$a, $b, $c, $r] = $money->splitWithRemainder(3); // USD 33.33, USD 33.33, USD 33.33, USD 0.01
```

```php
$profit = Money::of('987.65', 'CHF');
[$a, $b, $c, $r] = $profit->allocateWithRemainder(48, 41, 11); // CHF 474.08, CHF 404.93, CHF 108.64, CHF 0.01
```

```php
$profit = Money::of('987.65', 'CHF', new CashContext(5));
[$a, $b, $c, $r] = $profit->allocateWithRemainder(48, 41, 11); // CHF 474.05, CHF 404.90, CHF 108.60, CHF 0.10
```

**Comment by NCatalani** [comment]
Does the remainder needs to be appended at the end even on exact divisions?

**Comment by BenMorel** [comment]
@NCatalani I think so, yes. I'd rather get a `0 USD` remainder than having to check for existence of the nth value in the returned array.
