### ISSUE TITLE
GitHub Sponsors?

### ISSUE THREAD

**Issue by jkuchar** [brick/money#41]
Hi @BenMorel! I would like to ask if you have considered adding support for GitHub Sponsors / Patreon / Bitcoin address? Thanks! :-)

**Comment by BenMorel** [comment]
Hey @jkuchar! I've considered GitHub sponsors in the past, but never completed the process.
If you'd like to sponsor me I'll definitely move forward with it! 💛

**Comment by jkuchar** [comment]
Hi! I would like to thank you for the brilliant work you have done on this project. I think there would be more people around me who appreciate your work.

I would sponsor you. I do not think that my single donation will make economic sense to set up Github Sponsors. So hopefully, others will join also.

PS: If you would like to start with something simple, a Bitcoin address is the easiest if you have a wallet. Just generate an address and place it into readme.

**Comment by BenMorel** [comment]
Hi @jkuchar, thanks for your suggestions! I went ahead and activated my [GitHub Sponsors page](https://github.com/sponsors/BenMorel).

Thanks again 🙏

**Comment by jkuchar** [comment]
First sponsor. Thanks for awesome work! ❤️

**Comment by BenMorel** [comment]
I really appreciate it, @jkuchar. I'm glad to know that my libraries help people!

Thank you so much for being my first sponsor! :heart:
