### ISSUE TITLE
Issue with documentation of allocate()

### ISSUE THREAD

**Issue by nammet** [brick/money#45]
The readme says the following:

> When the allocation yields a remainder, both split() and allocate() spread it on the first monies in the list, until the total adds up to the original Money. This is the algorithm suggested by Martin Fowler in his book Patterns of Enterprise Application Architecture. You can see that in the first example, where the first money gets 33.34 dollars while the others get 33.33 dollars.

However it looks to me that split() spreads in the way described, but allocate appears to use the ratios to divide up the remainder:

```use Brick\Money\Money;

$profit = Money::ofMinor('1000', 'GBP');
[$a, $b, $c] = $profit->allocate(45, 20, 34); // GBP 45.50, GBP 20.20, GBP 34.30

**Comment by BenMorel** [comment]
Hi, the output of your script above is not the actual one, I'm not sure where you got it from. The actual output is:

```
GBP 4.55
GBP 2.02
GBP 3.43
```

Which is the correct output:

- 45/99 * 10 = 4.54...
- 20/99 * 10 = 2.02...
- 34/99 * 10 = 3.43...

Remainder = `0.01`, which is added to the first result so `4.55`.

**Comment by BenMorel** [comment]
Closing due to lack of feedback.
