### ISSUE TITLE
Question: how is operator overloading seemingly working?

### ISSUE THREAD

**Issue by bendavies** [brick/money#57]
Hi,

I can't work out how this is actaully working and gives correct results:

```php
<?php

use Brick\Math\BigDecimal;

var_dump(BigDecimal::of(1) > BigDecimal::zero());
var_dump(BigDecimal::of(1) >= BigDecimal::zero());
var_dump(BigDecimal::of(1) <= BigDecimal::zero());
var_dump(BigDecimal::of(1) < BigDecimal::zero());
```

What magic is PHP doing here?
I'm stumped!

**Comment by solodkiy** [comment]
May be it uses __toString() ?

**Comment by solodkiy** [comment]
Did you try more cases? Negative numbers, decimal, 11 vs 105 etc?

**Comment by bendavies** [comment]
We think php is comparing the internal properties of the objects (so `amount` and `scale`)

I've managed to break it now.

```php
var_dump(BigDecimal::of(100) > BigDecimal::ofUnscaledValue(1000, 2));
```

which is  `100 > 10` which should return true but returns false
