### ISSUE TITLE
Adding/Subtracting Money objects, but can't Multiply/Divide

### ISSUE THREAD

**Issue by devsi** [brick/money#60]
Currently add/subtract support giving an AbstractMoney instance so that something like `$first->add($second)` is a valid call. 

Why does multiply and divide not support this feature? They are effectively still mathematical operations and could be done on Abstracts also. 

Is this something you are looking to do in a future release, if not, what are the reasons why it wouldn't work?

Thanks :)

**Comment by BenMorel** [comment]
Hi, `AbstractMoney` does not have addition/subtraction at the moment, it only has comparison functions. Can you please explain what you mean?

**Comment by BenMorel** [comment]
Closing due to lack of feedback. Please feel free to comment if you wish this re-opened.
