### ISSUE TITLE
Requesting a release for brick/math 0.10 compatibility

### ISSUE THREAD

**Issue by bendavies** [brick/money#64]
hi there,

Do you think have a release, since https://github.com/brick/money/commit/8697f12ac6e7e742ede2330b1a401cc6c1f47aa8 was commit, so I can upgrade `brick/math` and `brick/money` in my projects?

Thanks!

**Comment by BenMorel** [comment]
Hi @bendavies, the next release will bring breaking changes, so I’d like to at least merge #62 before tagging a release. I have yet to receive feedback there, so if you’re up for it, please feel free to jump into the discussion to speed up the process!

**Comment by bendavies** [comment]
sure, will do!

**Comment by BenMorel** [comment]
@bendavies [0.6.0](https://github.com/brick/money/releases/tag/0.6.0) released with `brick/math` `0.10` compatibility!
