### ISSUE TITLE
Add a compareTo method

### ISSUE THREAD

**Issue by matutetandil** [brick/money#66]
Add a new method compareTo, in order to get if a value is equals to (0), greater than (1), or less than (-1) the given value.

```
$money = Money::of(50, 'USD');
$money1 = Money::of(60, 'USD');
$money2 = Money::of(60, 'USD');

echo $money->compareTo($money1); // -1 (less than)
echo $money1->compareTo($money); // 1 (greter than)
echo $money->compareTo($money2); // 0 (equals)
echo $money->compareTo($money); // 0 (equals)
```
If you try to compare two different currencies an error should be shown

**Comment by bendavies** [comment]
https://github.com/brick/money/blob/3709e60e0d9238e15153f62c136fed2ee37bc289/src/AbstractMoney.php#L124

**Comment by BenMorel** [comment]
As mentioned by @bendavies, the method is already implemented.
