### ISSUE TITLE
what is the default value of null price?

### ISSUE THREAD

**Issue by Huthaifah-kholi** [brick/money#71]
I'm using the "discount price" column in my e-commerce app. When there is no discount for the product the discount price is null, I want to check if this column is null or not in laravel view. 

It seems this package overrides the null value with another, who can I check if there is a discount price or not?

**Comment by BenMorel** [comment]
Hi, I don't understand your question, I think it's not a question related to the package itself, but to the integration you've done with Laravel?

**Comment by BenMorel** [comment]
Closing due to lack of feedback.
