### ISSUE TITLE
Calculations without currency. 

### ISSUE THREAD

**Issue by saffabook** [brick/money#72]
Hi, 

Is it possible to use brick money without currency?

For example Money::ofMinor($value); /// I want to add currency later on.

**Comment by BenMorel** [comment]
Hi, you can use [BigDecimal](https://github.com/brick/math/blob/master/src/BigDecimal.php) directly, which is used internally by `Money`.

`ofMinor()` without a currency would not make sense, as we don't know how many decimals a money has, until we have a currency.
