### ISSUE TITLE
Is it planned to support the distribution of funds by fractional ratios?

### ISSUE THREAD

**Issue by qnixdev** [brick/money#80]
Is it planned to support the distribution of funds by fractional ratios?

```php
$profit = Money::of('987.65', 'CHF');
[$a, $b, $c] = $profit->allocate(48.22, 41.03, 11);
```

**Comment by BenMorel** [comment]
Hi, I guess it shouldn't be hard to accept `BigNumber` instances in addition to `int`, I'll look into it!

In the meantime, you can just multiply each value by `100`.

**Comment by BenMorel** [comment]
You can now use integer, decimal, or rational numbers (as `BigNumber|int|string`) for ratios, plus you can now control the allocation algorithm through [AllocationMode](https://github.com/brick/money/blob/0.13.0/src/AllocationMode.php) in version [0.13.0](https://github.com/brick/money/releases/tag/0.13.0):

```php
$money = Money::of('987.65', 'CHF');

$money->allocate('48.22', '41.03', '11'], AllocationMode::FloorToFirst); // 475.06, 404.22, 108.37
```
