### ISSUE TITLE
Unknown currency code: CNH

### ISSUE THREAD

**Issue by mubashar-mtp** [brick/money#86]
exception: "Brick\\Money\\Exception\\UnknownCurrencyException"
file: "/vendor/brick/money/src/Exception/UnknownCurrencyException.php"
line: 14
message: "Unknown currency code: CNH"

**Comment by Wojtazzzz** [comment]
@mubashar-mtp library supports only ISO 4217 standard. CNH is not in this standard. But you can always create custom instance of this currency: https://github.com/brick/money?tab=readme-ov-file#custom-currencies

**Comment by BenMorel** [comment]
Exactly. Our currency list comes from [this list of ISO 4217 currencies](https://www.six-group.com/dam/download/financial-information/data-center/iso-currrency/lists/list-one.xml), and as you can see, `CNH` is not in it. See @Wojtazzzz's suggestion to use it with brick/money.
