### ISSUE TITLE
Allow decimal places for CVE, IDR, ISK, CLP

### ISSUE THREAD

**Issue by repli2dev** [brick/money#91]
It seems that the ISO norm for the decimal places is outdated and these four currencies at least are using the decimals as it seems to be mentioned on Adyen (payment gateway) docs: https://docs.adyen.com/development-resources/currency-codes/#note

Could it be added?

**Comment by BenMorel** [comment]
Hi @repli2dev, thanks for bringing this to my attention!

I'm a bit hesitant to go against the ISO standard here. Do you know if this is specific to Adyen, or if it's a common practice?

Also, from a quick search, I found that:

- 1 unit of these currencies is roughly equivalent to 1 cent of a EUR or USD, or less
- the average salary in the respective countries is typically on the order of 100,000 to 1,000,000 units

So I don't quite understand the need for decimals places in these currencies for everyday transactions? (And if you're looking for specific applications like trading, you can still use [custom scales](https://github.com/brick/money?tab=readme-ov-file#custom-scale)!)

**Comment by repli2dev** [comment]
It seems that the occurences exists due to two reasons:
* Technical (Adyen seems to fall into this category)
* Historical (CVE had decimals)

In the system I encountered this it seems that it is the technical reason as well (just mechanical computation).

So probably OK to close as won't fix
